window.BRIEFING_DATA = {
  "finnhub_key": "d8fo751r01qn443av1rgd8fo751r01qn443av1s0",
  "last_updated": "Initialized \u2014 first pipeline run pending",
  "run_type": "init",
  "regime": "Bullish",
  "regime_confidence": "High",
  "market_open": false,
  "vix": null,
  "vix_avg": null,
  "vix_trend": null,
  "vix_regime": "Yellow",
  "market_bullets": [
    "Dashboard initialized with live portfolio data",
    "Morning briefing will populate news, position review, and industry opportunities at 8:45 AM ET",
    "Afternoon update will run at 2:45 PM ET on trading days"
  ],
  "positions": [
    {
      "ticker": "SPY",
      "type": "Stock",
      "term": "Long-term",
      "qty": 6.32302,
      "entry_price": 659.44,
      "current_price": 744.39,
      "balance": 4706.79,
      "cost_basis": 4169.65,
      "pct_change": 12.88,
      "dollar_change": 537.14,
      "industry": "Broad Market ETF",
      "summary": "S&P 500 index ETF tracking the broad U.S. equity market. Core long-term holding providing broad market exposure.",
      "catalyst": "No specific catalyst \u2014 tracks overall market performance.",
      "why": "Long-term core holding. Provides stable broad market exposure when no higher-conviction opportunity exists for uninvested capital."
    },
    {
      "ticker": "MU",
      "type": "Stock",
      "term": "Medium-term",
      "qty": 0.24798,
      "entry_price": 599.21,
      "current_price": 1211.38,
      "balance": 300.4,
      "cost_basis": 148.59,
      "pct_change": 102.16,
      "dollar_change": 151.81,
      "industry": "Semiconductors",
      "summary": "Micron Technology is a leading manufacturer of DRAM and NAND memory chips, benefiting from AI-driven memory demand.",
      "catalyst": "Earnings in approximately 9 trading days \u2014 memory demand trends and AI server build-out guidance will be key.",
      "why": "Medium-term position built around the AI memory demand supercycle. Significant unrealized gain \u2014 pre-earnings exit rule applies."
    },
    {
      "ticker": "AMD",
      "type": "Stock",
      "term": "Medium-term",
      "qty": 0.58112,
      "entry_price": 453.74,
      "current_price": 551.63,
      "balance": 320.56,
      "cost_basis": 263.68,
      "pct_change": 21.57,
      "dollar_change": 56.89,
      "industry": "Semiconductors",
      "summary": "Advanced Micro Devices competes directly with NVIDIA in data center GPUs, with a growing share of the AI training and inference market.",
      "catalyst": "Q2 FY2026 earnings on August 4 \u2014 guided ~$11.2B revenue, up 46% YoY. Will show whether AI GPU share gains are materializing.",
      "why": "Medium-term position built around a multi-quarter GPU share-gain thesis against NVDA. Reassess materially at August 4 earnings."
    },
    {
      "ticker": "SPCX",
      "type": "Stock",
      "term": "Long-term",
      "qty": 1.28908,
      "entry_price": 183.84,
      "current_price": 154.6,
      "balance": 199.29,
      "cost_basis": 236.98,
      "pct_change": -15.91,
      "dollar_change": -37.69,
      "industry": "Aerospace & Space",
      "summary": "SpaceX, recently IPO'd, operates the dominant commercial launch business plus Starlink satellite internet with significant long-term optionality.",
      "catalyst": "Index inclusion dates through late June and early July may drive forced buying from Russell 1000, MSCI, and Nasdaq-100 index funds.",
      "why": "Long-term because the thesis is built around multi-year category leadership in launch and satellite infrastructure, not short-term post-IPO price action."
    },
    {
      "ticker": "CRWV",
      "type": "Stock",
      "term": "Medium-term",
      "qty": 0.5,
      "entry_price": 116.6,
      "current_price": 111.29,
      "balance": 55.65,
      "cost_basis": 58.3,
      "pct_change": -4.55,
      "dollar_change": -2.65,
      "industry": "AI Infrastructure",
      "summary": "CoreWeave is a specialized AI cloud provider offering GPU compute infrastructure, primarily serving AI model training workloads.",
      "catalyst": "Recently IPO'd \u2014 early commercial traction and hyperscaler contract announcements are the key near-term catalysts to watch.",
      "why": "Medium-term position in the AI infrastructure buildout. Conviction depends on continued GPU demand from model training and inference."
    },
    {
      "ticker": "NVDA",
      "type": "Stock",
      "term": "Long-term",
      "qty": 0.97402,
      "entry_price": 205.33,
      "current_price": 208.65,
      "balance": 203.23,
      "cost_basis": 200.0,
      "pct_change": 1.62,
      "dollar_change": 3.23,
      "industry": "AI Infrastructure",
      "summary": "NVIDIA is the dominant supplier of GPUs for AI training and inference, effectively the bellwether for global AI infrastructure capital spending.",
      "catalyst": "Q2 FY2027 earnings on August 26 \u2014 guided ~$91B in revenue. The single most important data point for the entire AI infrastructure trade.",
      "why": "Long-term core holding in the AI infrastructure buildout. Expected to be held for years absent a structural change to the thesis."
    },
    {
      "ticker": "HUM",
      "type": "Stock",
      "term": "Short-term",
      "qty": 0.13991,
      "entry_price": 357.37,
      "current_price": 360.72,
      "balance": 50.47,
      "cost_basis": 50.0,
      "pct_change": 0.94,
      "dollar_change": 0.47,
      "industry": "Managed Care",
      "summary": "Humana is a managed care insurer focused on Medicare Advantage plans, sensitive to CMS reimbursement rates and utilization trends.",
      "catalyst": "Q2 FY2026 earnings on July 29 \u2014 Medicare Advantage cost trends and full-year EPS guidance will determine whether the thesis holds.",
      "why": "Short-term position entered specifically around the July 29 earnings catalyst with a pre-earnings exit rule in place."
    },
    {
      "ticker": "PLTR",
      "type": "Stock",
      "term": "Medium-term",
      "qty": 1.0,
      "entry_price": 133.41,
      "current_price": 119.5,
      "balance": 119.5,
      "cost_basis": 133.41,
      "pct_change": -10.43,
      "dollar_change": -13.91,
      "industry": "Data Analytics",
      "summary": "Palantir provides AI-driven data analytics software to government and enterprise clients, with AIP as its fastest-growing product line.",
      "catalyst": "Q2 FY2026 earnings on August 10 \u2014 guided $1.797-$1.801B revenue, ~71% full-year growth. Validates AIP commercial momentum.",
      "why": "Medium-term position dependent on AIP adoption continuing to scale over several quarters. Valuation premium is a key risk to monitor."
    },
    {
      "ticker": "UFO",
      "type": "ETF",
      "term": "Long-term",
      "qty": 1.41896,
      "entry_price": 66.95,
      "current_price": 48.72,
      "balance": 69.13,
      "cost_basis": 95.0,
      "pct_change": -27.23,
      "dollar_change": -25.87,
      "industry": "Aerospace & Space",
      "summary": "Procure Space ETF provides exposure to companies involved in space-related industries including launch, satellites, and communications.",
      "catalyst": "No specific near-term catalyst \u2014 tracks broad space industry performance.",
      "why": "Long-term thematic holding in the space economy. Monitored separately from the active investment system."
    },
    {
      "ticker": "BTC",
      "type": "Crypto",
      "term": "Long-term",
      "qty": 0.04544048,
      "entry_price": 59767.28,
      "current_price": 63921.99,
      "balance": 2904.65,
      "cost_basis": 2715.85,
      "pct_change": 6.95,
      "dollar_change": 188.79,
      "industry": "Cryptocurrency",
      "summary": "Bitcoin held as a long-term store-of-value position. Monitored for macro liquidity conditions and regulatory developments.",
      "catalyst": "No company-specific catalyst \u2014 monitored against macro liquidity and regulatory environment.",
      "why": "Long-term structural allocation rather than a trade. Held through volatility, not actively traded around short-term price swings."
    },
    {
      "ticker": "ZEC",
      "type": "Crypto",
      "term": "Long-term",
      "qty": 1.00032929,
      "entry_price": 482.12,
      "current_price": 443.48,
      "balance": 443.63,
      "cost_basis": 482.28,
      "pct_change": -8.01,
      "dollar_change": -38.65,
      "industry": "Cryptocurrency",
      "summary": "Zcash is a privacy-focused cryptocurrency using zero-knowledge cryptography to enable shielded transactions.",
      "catalyst": "No specific near-term catalyst \u2014 monitored for broader crypto market conditions.",
      "why": "Long-term thematic position in privacy-preserving blockchain infrastructure."
    },
    {
      "ticker": "ETH",
      "type": "Crypto",
      "term": "Long-term",
      "qty": 0.2056305,
      "entry_price": 2010.52,
      "current_price": 1723.69,
      "balance": 354.44,
      "cost_basis": 413.42,
      "pct_change": -14.27,
      "dollar_change": -58.98,
      "industry": "Cryptocurrency",
      "summary": "Ethereum is the leading smart contract platform. 99% staked generating ~$0.53/month in staking rewards.",
      "catalyst": "No specific near-term catalyst \u2014 monitored for network upgrade developments and DeFi activity.",
      "why": "Long-term core crypto holding. Staking rewards provide yield while holding for long-term appreciation."
    },
    {
      "ticker": "XRP",
      "type": "Crypto",
      "term": "Long-term",
      "qty": 250.635305,
      "entry_price": 1.18,
      "current_price": 1.13,
      "balance": 283.22,
      "cost_basis": 295.75,
      "pct_change": -4.24,
      "dollar_change": -12.53,
      "industry": "Cryptocurrency",
      "summary": "XRP is used for cross-border payment settlement, with ongoing regulatory clarity improving its institutional adoption prospects.",
      "catalyst": "SEC litigation resolution and institutional payment partnerships are the key long-term catalysts.",
      "why": "Long-term position in digital payment infrastructure. Regulatory clarity is the primary thesis driver."
    }
  ],
  "cash": 0,
  "cost_basis": 9262.91,
  "vs_spy_pp": null,
  "performance_dates": [],
  "performance_portfolio": [],
  "performance_spy": [],
  "news": [],
  "forward_catalysts": [],
  "position_review": [],
  "industry_opportunities": [],
  "what_changed": [],
  "notable_moves": [],
  "afternoon_positions": [],
  "afternoon_candidates": []
};